main:
  uri: /
  param1: test
  param2: test2

main_v2:
  uri: /test
  class: \Router\Router
  route: sub/admin
  method: GET POST PUT

main_v3:
  uri: /sub
  route: admin

shop_test:
  uri: /shop/{shopName:string}
  route: sub/admin
  method: PUT